package com.example.graduateproject.utils

object Constants {
    const val DEVELOPER_EMAIL = "vilkova_viktoria2000@mail.ru"
    const val STUDY_WEEK_DAY = "week's day"
    const val STUDY_WEEK = "study week"
    const val SWITCH_PERMISSION_NOTIFICATION = "study notification"
    const val SAVED_PASSWORD = "password"
    const val UPDATED_SAVED_PASSWORD = "updated password"
    const val SAVED_EMAIL = "email"
    const val SAVED_MONTH_EXPENSE = "month budget"
    const val EXPENSE_ON_BOARDING = "expenses on boarding"
    const val SCHEDULE_ON_BOARDING = "schedule on boarding"
    const val NOTE_ON_BOARDING = "note on boarding"
    const val RATE_US = "rate app"
    const val VISITING_APP = "count of visit app"
    const val DIVIDER = "-"
    const val MONDAY = "Понедельник"
    const val FIRST_WEEK = "1 неделя"
    const val SECOND_WEEK = "2 неделя"
    const val WIDGET_ACTION = "android.appwidget.action.APPWIDGET_UPDATE"
    const val STUDY = "Учёба"
    const val FOOD = "Еда"
    const val SHOPPING = "Покупки"
    const val TRANSPORT = "Транспорт"
    const val HEALTH = "Здоровье"
    const val OTHER = "Другое"
    const val REMAINS = "Остаток"
}